# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss

# jekyll-seo-tag configuration
author: ""
url: ""
title: ""
description: ""
twitter:
  username: ""
  card: ""
logo: "path/to/image"

permalink: "/blog/:title/"

# https://github.com/mhanberg/jekyll-purgecss/issues/1
css_dir: "assets/css"

include:
  - "_pages"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - "*.js"
  - "*.log"
  - "yarn.*"
  - "*.lock"
  - "*.json"
  - "Gemfile"
  - ".DS_Store"
  - "README.md"
  - ".gitignore"
  - "node_modules"
